Repository prgrms-web-devcourse-final-project/WEB1_1_Bongdari_FE, pull requests merged in 2024-12, with the labels that each got.

#101 login page 상단 패딩 수정
  src/api/routes/index.tsx
  src/pages/login-page/LoginPageCss.ts
Labels: bug

#100 76 feature center profile page
  public/assets/imgs/mitten-blue.svg
  public/assets/imgs/mitten-green.svg
  public/assets/imgs/mitten-navy.svg
  public/assets/imgs/mitten-none.svg
  public/assets/imgs/mitten-orange.svg
  public/assets/imgs/mitten-purple.svg
  public/assets/imgs/mitten-rainbow.svg
  public/assets/imgs/mitten-red.svg
  public/assets/imgs/mitten-yellow.svg
  src/api/routes/index.tsx
  src/features/center-profile-top/_components/ProfilePreferItemBox.tsx
  src/features/center-profile-top/_components/ProfilePreferItemBoxCss.ts
  src/features/center-profile-top/index.tsx
  src/features/center-profile-top/indexCss.tsx
  src/features/profile-page-img-box/index.tsx
  src/features/profile-page-img-box/indexCss.ts
  src/features/profile-page-info-box/index.tsx
  src/features/profile-page-info-box/indexCss.ts
  src/pages/center-profile-page/CenterProfilePage.tsx
  src/pages/center-profile-page/CenterProfilePageCss.ts
  src/pages/personal-profile-page/PersonalProfilePage.tsx
  src/pages/personal-profile-page/PersonalProfilePageCss.ts
  src/shared/types/center-profile/centerProfile.ts
  src/shared/types/person-profile/personProfile.ts
Labels: Feature

#114 🐛Fixed: CICD오류 디버깅
  src/features/login-feature/_components/person-login/index.tsx
  src/features/profile-page-img-box/index.tsx
Labels: Feature

#120 🐛bug:CICD오류 디버깅
  src/pages/admin-aidrq-list-page/_components/aidrqlistadmin-wrapper/index.tsx
Labels: bug

#123 ✨feat : aidrqlistpage 2차개발 완료
  src/components/aidreq-list-Item/index.tsx
  src/components/aidreq-list-Item/ui/top/index.tsx
  src/components/search-bar/filter-search/ui/filter-box/index.tsx
  src/features/aidrq-create-shared-part/index.tsx
  src/features/aidrq-list-admin/index.tsx
  src/features/aidrq-list-main-page/index.tsx
  src/pages/aidrq-create-page/index.tsx
  src/pages/aidrq-detail-page/ui/title/index.tsx
  src/pages/aidrq-list-page/ui/aidrqlist-wrapper/index.tsx
  src/pages/aidrq-list-page/ui/aidrqlist-wrapper/indexCss.ts
  src/pages/aidrq-list-page/ui/search/index.tsx
  src/pages/aidrq-list-page/ui/tab/index.tsx
  src/shared/mapping/aidrq-category-mapping.ts
  src/shared/types/aidrq-create-type/AidRqCreateType.ts
  src/shared/types/aidrq-detail/aidrqDetailType.ts
  src/shared/types/aidrq-list-item/aidrqListItemType.ts
  src/store/stores/search/searchStore.ts
Labels: Feature

#132 ✨feat: 알림 ui개발
  public/assets/imgs/alert-icon.svg
  src/components/alert-item/index.tsx
  src/components/alert-item/indexCss.ts
  src/features/alert/index.tsx
  src/features/alert/indexCss.ts
  src/layout/header/Header.tsx
  src/layout/header/HeaderCss.ts
  src/shared/types/alert-type/AlertType.ts
Labels: Feature

#136 ✨[#135]Feat : 알림 SSE연결 설정 완료
  src/features/alert/index.tsx
  src/layout/header/Header.tsx
Labels: Feature

#141 ✨feat : 알림 토스트 및 알림전체조회 및 읽기기능 구현
  package.json
  src/components/alert-item/index.tsx
  src/components/alert-item/indexCss.ts
  src/features/alert/index.tsx
  src/features/alert/logic/single-read/index.ts
  src/layout/header/Header.tsx
  yarn.lock
Labels: Feature

#145 ✨[#144]Feat: mainpage-api연결 1차작업 개발완료
  src/features/aidrq-list-main-page/index.tsx
  src/features/aidrq-list-main-page/logic/fetchListShort.ts
  src/pages/aidrq-detail-page/logic/fetchAidRqDetail.ts
  src/pages/aidrq-detail-page/logic/fetchCenterProfile.ts
  src/pages/main-page/MainPage.tsx
  src/pages/main-page/_components/aidrq-recent-list/index.tsx
  src/pages/main-page/_components/ranking/index.tsx
  src/pages/main-page/_components/ranking/logic/fetchRanking.ts
  src/pages/main-page/_components/ranking/ui/rank-item/index.tsx
  src/shared/types/ranking-data/RankingDataType.ts
Labels: Feature

#148 131 feature person my page api 연결
  public/assets/imgs/no-img-center.svg
  public/assets/imgs/no-img-person.svg
  src/api/routes/index.tsx
  src/features/input-with-label/InputWithLabel.tsx
  src/features/input-with-label/InputWithLabelCss.ts
  src/features/personal-my-page-edit-profile/_component/EditProfileImg.tsx
  src/features/personal-my-page-edit-profile/_component/EditProfileImgCss.ts
  src/features/personal-my-page-edit-profile/_component/logic/pickProfileImg.ts
  src/features/personal-my-page-edit-profile/index.tsx
  src/features/personal-my-page-edit-profile/indexCss.ts
  src/features/personal-my-page-feature/_components/half-list/index.tsx
  src/features/personal-my-page-feature/_components/heart-org-list/index.tsx
  src/features/personal-my-page-feature/_components/heart-org-list/indexCss.ts
  src/features/personal-my-page-feature/_components/heart-org-list/org-box/OrgBox.tsx
  src/features/personal-my-page-feature/_components/review-list/index.tsx
  src/features/personal-my-page-half-list/index.tsx
  src/features/personal-my-page-half-list/indexCss.ts
  src/features/personal-my-page-half-list/logic/onClickHalfList.ts
  src/features/personal-my-page-half-list/logic/useHalfList.ts
  src/features/personal-my-page-interest-center-list/_component/InterestCenterBox.tsx
  src/features/personal-my-page-interest-center-list/_component/InterestCenterBoxCss.ts
  src/features/personal-my-page-interest-center-list/index.tsx
  src/features/personal-my-page-interest-center-list/indexCss.ts
  src/features/personal-my-page-interest-center-list/logic/useMyInterestCenter.ts
  src/features/personal-my-page-review-list/_component/ReviewBox.tsx
  src/features/personal-my-page-review-list/_component/ReviewBoxCss.ts
  src/features/personal-my-page-review-list/index.tsx
  src/features/personal-my-page-review-list/indexCss.ts
  src/features/personal-my-page-review-list/logic/useMyReview.ts
  src/features/personal-my-page-title-with-pagenation/index.tsx
  src/features/personal-my-page-title-with-pagenation/indexCss.ts
  src/pages/personal-my-page/PersonalMyPageCss.ts
  src/pages/personal-my-page/_component/PMPGHalfLists.tsx
  src/pages/personal-my-page/_component/PMPGHalfListsCss.ts
  src/pages/personal-my-page/_component/PMPGTop.tsx
  src/pages/personal-my-page/_component/PMPGTopCss.ts
  src/pages/personal-my-page/_component/logic/fetchMyData.ts
  src/pages/personal-my-page/_component/logic/useMyAidData.ts
  src/pages/personal-my-page/_component/logic/useMyMessageData.ts
  src/pages/personal-my-page/_component/logic/useMyProfileData.ts
  src/pages/personal-my-page/index.tsx
  src/pages/personal-my-page/indexCss.ts
  src/shared/types/person-profile/personProfile.ts
Labels: Feature

#150 ✨feat: landingpage ui 개발완료 및 loginpage ui개선
  public/assets/imgs/landing-visual.svg
  src/api/routes/index.tsx
  src/features/login-feature/_components/org-login/indexCss.ts
  src/features/login-feature/_components/person-login/index.tsx
  src/pages/landing-page/index.tsx
  src/pages/landing-page/indexCss.ts
  src/pages/login-page/LoginPageCss.ts
Labels: Feature

#153 ✨[#152]Feat : aidrqDetailPage api연결
  public/assets/imgs/recruit-closed.svg
  public/assets/imgs/recruit-completed.svg
  src/api/routes/index.tsx
  src/features/aidreq-detail-info/_components/current-recruit/index.tsx
  src/features/aidreq-detail-info/_components/current-recruit/logic/fetchCurrentRecruitment.ts
  src/features/aidrq-list-main-page/index.tsx
  src/features/aidrq-list-regular/index.tsx
  src/pages/aidrq-detail-page/index.tsx
  src/pages/aidrq-detail-page/logic/applyAidRq.ts
  src/pages/aidrq-detail-page/logic/fetchAidRqDetail.ts
  src/pages/aidrq-detail-page/logic/fetchCenterProfile.ts
  src/pages/aidrq-detail-page/ui/text-content/index.tsx
  src/shared/types/aidrq-detail/aidrqDetailType.ts
  src/shared/types/recruitment-state/recruitmentStateType.ts
Labels: Feature

#154 130 feature center profile page api 연결
  src/api/routes/index.tsx
  src/features/center-profile-prefer-item-box/index.tsx
  src/features/center-profile-prefer-item-box/indexCss.ts
  src/features/center-profile-top/index.tsx
  src/features/community-list/index.tsx
  src/features/custom-pagnation/index.tsx
  src/features/custom-pagnation/indexCss.ts
  src/features/manage-center-post-set/_components/review-set/ReviewList.tsx
  src/features/manage-center-post-set/_components/review-set/index.tsx
  src/features/manage-center-post-set/_components/review-set/indexCss.ts
  src/features/profile-page-img-box/index.tsx
  src/pages/center-profile-page/_component/CPPGReviewList.tsx
  src/pages/center-profile-page/_component/CPPGReviewListCss.ts
  src/pages/center-profile-page/_component/CPPGTop.tsx
  src/pages/center-profile-page/_component/CPPGTopCss.ts
  src/pages/center-profile-page/_component/logic/fetchCenterData.ts
  src/pages/center-profile-page/_component/logic/useCenterProfile.ts
  src/pages/center-profile-page/_component/logic/useCenterReview.ts
  src/pages/center-profile-page/index.tsx
  src/pages/center-profile-page/indexCss.ts
  src/pages/personal-profile-page/logic/fetchPersonProfile.ts
  src/pages/personal-profile-page/logic/usePersonProfile.ts
  src/shared/types/center-profile/centerProfile.ts
  src/shared/types/person-profile/personProfile.ts
Labels: Feature

#163 ✨[#156]Feat:로그인모킹구현 지원하기api테스트 성공
  package.json
  src/api/apis/index.tsx
  src/features/login-feature/_components/org-login/logic/testLoginCenter.ts
  src/features/login-feature/_components/org-login/logic/useOrgLogin.ts
  src/features/login-feature/_components/person-login/index.tsx
  src/features/login-feature/_components/person-login/logic/testLoginPerson.ts
  src/features/login-feature/logic/example.ts
  src/pages/aidrq-detail-page/logic/applyAidRq.ts
  yarn.lock
Labels: Feature

#165 ✨feat:목업로그인 아이디변경
  src/features/aidreq-detail-center-profile/_components/button-container/index.tsx
  src/features/login-feature/_components/org-login/logic/testLoginCenter.ts
  src/features/login-feature/_components/org-login/logic/useOrgLogin.ts
  src/features/login-feature/_components/person-login/index.tsx
  src/features/login-feature/_components/person-login/logic/testLoginPerson.ts
  src/pages/aidrq-detail-page/index.tsx
  src/pages/aidrq-detail-page/logic/myPresentStatus.ts
  src/store/stores/login/loginStore.ts
Labels: Feature

#169 ✨[#168]Feat:aidrq디테일페이지 개발 3차
  src/pages/aidrq-detail-page/index.tsx
  src/pages/aidrq-detail-page/indexCss.ts
  src/pages/aidrq-detail-page/logic/myPresentStatus.ts
  src/pages/main-page/_components/community/logic/fetchMainCommunity.ts
Labels: Feature

#171 ✨[#170]feat:aidrq작성 api개발
  src/components/aidrq-create-date/index.tsx
  src/components/aidrq-create-location/index.tsx
  src/features/aidrq-create-shared-part/index.tsx
  src/features/aidrq-create-shared-part/ui/select-container/index.tsx
  src/pages/aidrq-create-page/index.tsx
  src/pages/aidrq-create-page/logic/postAidRq.ts
  src/pages/aidrq-create-page/ui/location/index.tsx
  src/pages/aidrq-create-page/ui/volunteer-date/index.tsx
  src/shared/types/aidrq-create-type/AidRqCreateType.ts
Labels: Feature

#175 🐛fix:cicd오류 디버깅
  src/pages/aidrq-modify-page/ui/location-modify/index.tsx
Labels: bug

#188 ✨feat:aidrq수정페이지 1차작업완료-location수정
  src/components/aidrq-create-location/index.tsx
  src/pages/aidrq-modify-page/index.tsx
  src/pages/aidrq-modify-page/logic/fetchAidRqDefault.ts
  src/pages/aidrq-modify-page/ui/location-modify/index.tsx
  src/pages/aidrq-modify-page/ui/location-modify/logic/modifyAidRqLocation.ts
  src/shared/types/aidrq-detail/aidrqDetailType.ts
Labels: Feature

#190 ✨Feat: 로그인테스트
  src/features/login-feature/_components/person-login/index.tsx
  src/layout/header/Header.tsx
  src/layout/header/logic/centerLogout.ts
  src/layout/header/logic/personLogout.ts
Labels: Feature

#192 ✨Bug:cicd디버깅
  src/pages/aidrq-create-page/ui/location/index.tsx
Labels: bug

#194 ✨feat:로그인구현테스트1차
  src/features/login-feature/_components/org-login/logic/testLoginCenter.ts
  src/features/login-feature/_components/org-login/logic/useOrgLogin.ts
  src/features/login-feature/_components/person-login/index.tsx
  src/pages/main-page/MainPage.tsx
Labels: Feature

#196 ✨feat:로그인2차테스트
  src/pages/main-page/MainPage.tsx
Labels: bug

#198 ✨feat: 토큰 오류 수정
  src/api/apis/index.tsx
Labels: bug

#200 ✨fix:center로그인데이터구조변경
  src/features/login-feature/_components/org-login/logic/testLoginCenter.ts
Labels: bug

#202 ✨fix:login디버깅3차
  package.json
  src/layout/header/Header.tsx
  src/pages/main-page/MainPage.tsx
  yarn.lock
Labels: bug

#203 201 feature sse테스트용브랜치
  src/api/apis/index.tsx
  src/pages/main-page/MainPage.tsx
Labels: bug

#205 ✨feat:로컬테스트용 로그인모킹 복구
  src/components/interest-heart/logic/useInterest.ts
  src/layout/header/Header.tsx
  src/pages/aidrq-detail-page/index.tsx
  src/pages/main-page/MainPage.tsx
  src/pages/main-page/_components/localTestBox/index.tsx
  src/pages/main-page/_components/localTestBoxVolun/index.tsx
  src/store/stores/login/loginStore.ts
Labels: Feature

#211 ✨feat: api요청설정 및 모킹로그인과 userinfoapi연결
  src/layout/header/logic/centerLogout.ts
  src/layout/header/logic/personLogout.ts
  src/pages/aidrq-detail-page/logic/applyAidRq.ts
  src/pages/main-page/_components/localTestBox/index.tsx
  src/pages/main-page/_components/localTestBoxVolun/index.tsx
Labels: Feature

#213 ✨feat:지원하기 및 등록하기 api 수정 완료
  src/components/inputBox/index.tsx
  src/components/inputBox/logic/useInput.ts
  src/pages/aidrq-create-page/logic/postAidRq.ts
  src/pages/aidrq-detail-page/logic/applyAidRq.ts
  src/pages/main-page/_components/localTestBox/index.tsx
Labels: Feature

#220 🐛 [#217] Bug: 수정완료
  src/features/communitiy-detail-comment-box/logic/fetchCommunityComment.ts
  src/features/communitiy-detail-comment-box/logic/useCommunityComment.ts
  src/features/communitiy-detail-comment-box/ui/CommentCss.ts
  src/features/communitiy-detail-comment-box/ui/CommentReplyInput.tsx
  src/features/communitiy-detail-comment-box/ui/logic/useComment.ts
  src/features/community-list/index.tsx
  src/features/community-list/logic/fetchCommunityList.ts
  src/features/community-list/logic/useCommunityList.ts
  src/pages/main-page/_components/community/index.tsx
  src/pages/personal-my-page/_component/logic/fetchMyData.ts
  src/styles/global.ts
Labels: bug

#221 ✨feat:토큰수정테스트
  src/pages/main-page/MainPage.tsx
Labels: Feature

#223 ✨feat:토큰테스트/지원하기등록하기테스트
  src/layout/header/logic/centerLogout.ts
  src/layout/header/logic/personLogout.ts
  src/pages/aidrq-create-page/logic/postAidRq.ts
  src/pages/aidrq-detail-page/logic/applyAidRq.ts
Labels: Feature

#225 ✨feat:Header설정 및 sse1차테스트
  src/features/alert/index.tsx
  src/layout/header/Header.tsx
  src/layout/header/HeaderCss.ts
Labels: Feature

#226 180 feature community create page api 연결
  src/components/textArea/index.tsx
  src/features/communitiy-detail-comment-box/logic/fetchCommunityComment.ts
  src/features/communitiy-detail-content-box/logic/fetchCommunityDetailContent.ts
  src/features/communitiy-detail-content-box/logic/useCommunityDetailContent.ts
  src/features/community-create-box/index.tsx
  src/features/community-create-box/logic/postCommunity.ts
  src/features/community-create-box/logic/useCreateCommunity.ts
  src/features/community-list/index.tsx
  src/shared/types/resType.ts
Labels: Feature

#230 sse세부디버깅 및 로그인버그개선
  src/layout/header/Header.tsx
  src/pages/main-page/MainPage.tsx
Labels: bug

#232 🐛 [#231] BUG: CICD error fix
  src/features/communitiy-detail-comment-box/logic/fetchCommunityComment.ts
Labels: bug

#233 Feat/#174/지원자리스트
  src/api/routes/index.tsx
  src/components/applicant-list-item/index.tsx
  src/components/applicant-list-item/indexCss.ts
  src/components/button/other-button/indexCss.ts
  src/features/adjustment-modal/index.tsx
  src/features/aidreq-detail-admin-info/_components/applicant-status/index.tsx
  src/features/aidreq-detail-admin-info/_components/application-period/index.tsx
  src/features/aidreq-detail-admin-info/index.tsx
  src/features/aidreq-detail-admin-recruit-state/index.tsx
  src/features/aidreq-detail-admin-recruit-state/indexCss.ts
  src/features/applicant-detail-modal/index.tsx
  src/features/applicant-list/index.tsx
  src/features/edit-center-profile/_components/image-uploader/index.tsx
  src/features/edit-center-profile/_components/profile-edit-form/index.tsx
  src/features/edit-center-profile/index.tsx
  src/features/edit-center-profile/logic/useEditCenterProfile.ts
  src/features/edit-center-profile/logic/useSubmitCenterProfile.ts
  src/features/register-goods/_components/register-bar/index.tsx
  src/features/register-goods/index.tsx
  src/features/register-goods/logic/useAddItem.ts
  src/pages/admin-aidrq-list-page/index.tsx
  src/pages/aidrq-applicant-list-page/index.tsx
  src/pages/aidrq-applicant-list-page/indexCss.ts
  src/pages/aidrq-applicant-list-page/ui/title/index.tsx
  src/pages/aidrq-detail-admin-page/index.tsx
  src/pages/aidrq-detail-admin-page/ui/button-group/index.tsx
  src/pages/center-my-page/index.tsx
  src/shared/hooks/useImageUpload.ts
  src/shared/hooks/useInfiniteAidRq.ts
  src/store/queries/aidreq-detail-center/useAidRqDetail.ts
  src/store/queries/aidreq-detail-center/useApplicant.ts
  src/store/queries/aidreq-detail-center/useApplicantDetail.ts
  src/store/queries/aidreq-detail-center/useManageApplyment.ts
  src/store/queries/aidreq-detail-center/useRecruitBoard.ts
  src/store/queries/center-mypage/useCenterProfile.ts
  src/store/queries/center-mypage/usePreferItems.ts
Labels: Feature

#236 ✨feat:마이페이지라우팅처리 및 sse디버깅
  src/api/routes/index.tsx
  src/layout/header/Header.tsx
  src/layout/header/HeaderCss.ts
Labels: Feature

#238 🐛fix:centermypage라우팅수정
  src/components/write-aidreq-button/index.tsx
  src/features/aidreq-detail-admin-info/_components/applicant-status/index.tsx
  src/features/aidrq-list-admin/index.tsx
  src/features/manage-center-post-set/_components/go-aidreq-set/index.tsx
  src/pages/aidrq-detail-admin-page/ui/button-group/index.tsx
Labels: bug

#240 ✨[#239]feat:수정하기페이지 개발
  src/components/aidrq-create-date/index.tsx
  src/components/aidrq-create-recruit-population/index.tsx
  src/components/select/index.tsx
  src/features/aidrq-create-shared-part/index.tsx
  src/features/aidrq-create-shared-part/ui/select-container/index.tsx
  src/pages/aidrq-create-page/index.tsx
  src/pages/aidrq-create-page/ui/recruit-population/index.tsx
  src/pages/aidrq-create-page/ui/volunteer-date/index.tsx
  src/pages/aidrq-detail-admin-page/index.tsx
  src/pages/aidrq-detail-admin-page/ui/button-group/index.tsx
  src/pages/aidrq-modify-page/index.tsx
  src/pages/aidrq-modify-page/ui/info-modify/index.tsx
  src/pages/aidrq-modify-page/ui/info-modify/logic/modifyAidRqRegular.ts
  src/pages/aidrq-modify-page/ui/location-modify/index.tsx
  src/pages/aidrq-modify-page/ui/location-modify/logic/modifyAidRqLocation.ts
Labels: Feature

#242 ✨feat:notification연결및읽기기능구현
  src/components/alert-item/index.tsx
  src/features/alert/index.tsx
  src/features/alert/logic/single-read/index.ts
Labels: Feature

#244 ✨feat:notification작업완료
  src/components/alert-item/index.tsx
  src/components/alert-item/indexCss.ts
  src/features/alert/index.tsx
  src/layout/header/Header.tsx
  src/layout/header/HeaderCss.ts
  src/shared/types/alert-type/AlertType.ts
Labels: Feature

#251 ✨feat:리뷰구현
  src/features/review-create-modal/index.tsx
  src/features/review-create-modal/logic/createReview.ts
  src/features/review-create-modal/logic/handleFileSelect.ts
Labels: Feature

#254 🐛 [#253] BUG: CICD Fix
  src/features/communitiy-detail-comment-box/logic/useCommunityComment.ts
  src/pages/center-profile-page/_component/logic/useCenterReview.ts
Labels: bug

#255 228 feature 기관 개인 프로필 페이지 쪽지 api 연결
  src/features/communitiy-detail-comment-box/logic/fetchCommunityComment.ts
  src/features/message-create-modal/logic/postMessage.ts
  src/features/message-create-modal/logic/useSendMail.ts
  src/features/profile-page-img-box/index.tsx
Labels: Feature

#259 ✨feat:리뷰 수정
  src/features/review-create-modal/index.tsx
  src/features/review-create-modal/logic/createReview.ts
  src/pages/aidrq-detail-page/index.tsx
Labels: bug

#261 257 fix 개인마이페이지 버그 수정
  src/components/interest-heart/logic/putInterest.ts
  src/features/communitiy-detail-comment-box/logic/useCommunityComment.ts
  src/features/communitiy-detail-comment-box/ui/logic/useCommentReplyInput.ts
  src/features/communitiy-detail-content-box/logic/useCommunityDetailContent.ts
  src/features/communitiy-detail-content-box/ui/WriterProfileBox.tsx
  src/features/community-create-box/logic/postCommunity.ts
  src/features/community-list/logic/useCommunityList.ts
  src/features/message-read-modal/index.tsx
  src/features/personal-my-page-edit-profile/logic/putMyProfile.ts
  src/features/personal-my-page-edit-profile/logic/useEditMyProfile.ts
  src/features/personal-my-page-half-list/index.tsx
  src/features/personal-my-page-half-list/logic/useHalfList.ts
  src/features/personal-my-page-interest-center-list/_component/InterestCenterBox.tsx
  src/features/personal-my-page-interest-center-list/_component/InterestCenterBoxCss.ts
  src/features/personal-my-page-interest-center-list/index.tsx
  src/features/personal-my-page-interest-center-list/logic/useMyInterestCenter.ts
  src/features/personal-my-page-review-list/logic/useMyReview.ts
  src/features/profile-page-img-box/index.tsx
  src/features/profile-page-info-box/index.tsx
  src/pages/center-profile-page/_component/logic/useCenterProfile.ts
  src/pages/center-profile-page/_component/logic/useCenterReview.ts
  src/pages/personal-my-page/_component/logic/useMyProfileData.ts
  src/pages/personal-profile-page/logic/usePersonProfile.ts
  src/store/queries/center-mypage/useReview.ts
Labels: bug

#263 ✨feat: notification수정
  src/components/alert-item/index.tsx
  src/features/alert/index.tsx
  src/layout/header/Header.tsx
  src/shared/types/alert-type/AlertType.ts
Labels: Feature

#265 ✨[#264]Feat:메인페이지수정 및 디테일페이지 분류
  src/pages/aidrq-detail-page/index.tsx
  src/pages/aidrq-detail-page/logic/applyAidRq.ts
  src/pages/main-page/MainPage.tsx
  src/pages/main-page/MainpageCss.ts
Labels: Feature

#270 🐛이미지사라짐오류디버깅/status오류디버깅
  src/features/main-banner/indexCss.ts
  src/layout/header/Header.tsx
  src/pages/aidrq-list-page/ui/aidrqlist-wrapper/index.tsx
  src/pages/main-page/_components/ranking/ui/rank-item/index.tsx
Labels: bug

#272 🐛[#271]Fix:지원물품리스트 및 지원하기버튼css 디버깅
  src/features/aidreq-detail-center-profile/_components/info-container/index.tsx
  src/pages/aidrq-detail-page/index.tsx
  src/pages/aidrq-detail-page/indexCss.ts
  src/shared/types/center-profile/centerProfile.ts
Labels: bug

#275 262 fix 쪽지 관심기관 하트 api 연결 오류
  src/components/interest-heart/index.tsx
  src/components/interest-heart/logic/useInterest.ts
  src/features/message-create-modal/logic/postMessage.ts
  src/features/message-create-modal/logic/useSendMail.ts
  src/features/profile-page-img-box/index.tsx
  src/pages/main-page/_components/community/indexCss.ts
Labels: bug

#276 ✨feat:랜딩페이지연결
  src/api/routes/index.tsx
  src/layout/header/Header.tsx
Labels: Feature

#287 277 fix 커뮤니티 오류 해결
  src/components/interest-heart/logic/putInterest.ts
  src/components/interest-heart/logic/useInterest.ts
  src/components/long-list-item/indexCss.ts
  src/features/communitiy-detail-comment-box/ui/Comment.tsx
  src/features/communitiy-detail-content-box/index.tsx
  src/features/communitiy-detail-content-box/logic/useCommunityDetailContent.ts
  src/features/community-list/logic/fetchCommunityList.ts
  src/features/message-create-modal/index.tsx
  src/features/message-create-modal/logic/postMessage.ts
  src/features/message-create-modal/logic/useSendMail.ts
  src/features/personal-my-page-interest-center-list/_component/InterestCenterBoxCss.ts
  src/features/profile-page-img-box/index.tsx
  src/styles/global.ts
Labels: bug

#299 ♻️Refactor:type공유 및 오류디버깅
  src/api/routes/index.tsx
  src/components/aidreq-list-Item/index.tsx
  src/components/aidreq-list-Item/ui/top/index.tsx
  src/components/applicant-list-item/index.tsx
  src/components/interest-heart/logic/putInterest.ts
  src/components/search-bar/filter-search/logic/testFunc.ts
  src/components/search-bar/nonfilter-search/index.tsx
  src/components/search-bar/nonfilter-search/logic/testFunc.ts
  src/features/adjustment-modal/index.tsx
  src/features/aidreq-detail-center-profile/_components/picture-container/index.tsx
  src/features/applicant-list/index.tsx
  src/features/center-profile-prefer-item-box/index.tsx
  src/features/communitiy-detail-comment-box/logic/useCommunityComment.ts
  src/features/edit-center-profile/index.tsx
  src/features/edit-center-profile/logic/useEditCenterProfile.ts
  src/features/login-feature/_components/person-login/index.tsx
  src/features/manage-center-post-set/_components/message-set/index.tsx
  src/features/manage-center-post-set/_components/review-set/index.tsx
  src/features/personal-my-page-half-list/logic/onClickHalfList.ts
  src/features/register-goods/index.tsx
  src/features/review-create-modal/index.tsx
  src/pages/aidrq-detail-page/index.tsx
  src/pages/main-page/PostCode.tsx
  src/pages/test-page/index.tsx
  src/shared/types/aidrq-detail/PresentResponse.ts
  src/shared/types/aidrq-detail/aidrqDetailType.ts
  src/shared/types/aidrq-volunteer-list/volunteerListType.ts
  src/shared/types/interest/interestType.ts
  src/shared/types/location/locationType.ts
  src/shared/types/message/messageItemType.ts
  src/shared/types/person-profile/personProfile.ts
  src/shared/types/resType.ts
  src/shared/types/review/reviewType.ts
  src/store/queries/aidreq-control-center-query/useModifyAidRqLocation.ts
  src/store/queries/aidreq-control-center-query/useModifyAidRqRegular.ts
  src/store/queries/aidreq-detail-admin-query/useAidRqDetail.ts
  src/store/queries/aidreq-detail-admin-query/useApplicant.ts
  src/store/queries/aidreq-detail-admin-query/useApplicantDetail.ts
  src/store/queries/aidreq-detail-volunteer-query/useCurrentRecruitment.ts
  src/store/queries/aidreq-detail-volunteer-query/useFetchAidRqDetail.ts
  src/store/queries/aidreq-detail-volunteer-query/useFetchCenterProfile.ts
  src/store/queries/aidreq-detail-volunteer-query/usePresentStatus.ts
  src/store/queries/center-mypage/useCenterProfile.ts
  src/store/queries/center-mypage/useMessage.ts
  src/store/queries/center-mypage/usePreferItems.ts
  src/store/queries/center-mypage/useReview.ts
  src/store/queries/community-detail-common-query/useCommunityComment.ts
  src/store/queries/interest-heart-query/useInterestHeart.ts
  src/store/queries/login-query/useLoginVolunteer.ts
  src/store/queries/main-page-common-query/useListShort.ts
  src/store/queries/volunteer-profile/useVolunteerProfile.ts
Labels: enhancement

#301 🐛bug:CICD오류개선
  src/store/queries/community-detail-common-query/useCommunityComment.ts
Labels: bug

#306 ✨feat:communitylist reactquery로 변경
  src/features/community-list/index.tsx
  src/features/community-list/logic/useCommunityList.ts
  src/store/queries/community-list-common-query/useCommunityList.ts
Labels: Feature

#309 ✨feat: aidrq detail기능 reactquery로 변경
  src/features/aidreq-detail-info/_components/current-recruit/index.tsx
  src/pages/aidrq-detail-page/index.tsx
  src/store/queries/aidreq-detail-volunteer-query/useApplyAidRq.ts
  src/store/queries/aidreq-detail-volunteer-query/useCurrentRecruitment.ts
  src/store/queries/aidreq-detail-volunteer-query/useFetchAidRqDetail.ts
  src/store/queries/aidreq-detail-volunteer-query/useFetchCenterProfile.ts
  src/store/queries/aidreq-detail-volunteer-query/usePresentStatus.ts
Labels: Feature

#311 ✨feat: aidrq post부분과 modify default get부분 react query처리
  src/components/aidrq-create-recruit-population/index.tsx
  src/pages/aidrq-create-page/index.tsx
  src/pages/aidrq-modify-page/index.tsx
  src/pages/aidrq-modify-page/ui/info-modify/index.tsx
  src/pages/aidrq-modify-page/ui/location-modify/index.tsx
  src/store/queries/aidreq-control-center-query/useFetchAidRqDefault.ts
  src/store/queries/aidreq-control-center-query/useModifyAidRqRegular.ts
  src/store/queries/aidreq-control-center-query/usePostAidRq.ts
  src/store/queries/aidreq-detail-volunteer-query/useApplyAidRq.ts
  src/store/queries/aidreq-detail-volunteer-query/useFetchAidRqDetail.ts
Labels: Feature

#315 ✨feat: 작성 수정 지원 등에 dialog추가
  src/components/applicant-list-item/index.tsx
  src/pages/aidrq-create-page/index.tsx
  src/pages/aidrq-detail-page/index.tsx
  src/pages/aidrq-modify-page/ui/info-modify/index.tsx
  src/pages/aidrq-modify-page/ui/info-modify/indexCss.ts
  src/pages/aidrq-modify-page/ui/location-modify/index.tsx
  src/pages/aidrq-modify-page/ui/location-modify/indexCss.ts
Labels: Feature

#316 ♻️ [#314] Refactor: 버튼 컴포넌트 통합
  src/components/applicant-list-item/index.tsx
  src/components/button/index.tsx
  src/components/button/indexCss.ts
  src/components/button/other-button/index.tsx
  src/components/button/other-button/indexCss.ts
  src/components/button/submit-button/index.tsx
  src/components/button/submit-button/indexCss.ts
  src/components/search-bar/filter-search/ui/filter-box/index.tsx
  src/components/search-bar/nonfilter-search/index.tsx
  src/features/adjustment-modal/index.tsx
  src/features/aidreq-detail-admin-recruit-state/index.tsx
  src/features/aidreq-detail-admin-recruit-state/indexCss.ts
  src/features/aidreq-detail-center-profile/_components/button-container/index.tsx
  src/features/communitiy-detail-comment-box/ui/CommentInput.tsx
  src/features/communitiy-detail-content-box/index.tsx
  src/features/communitiy-detail-content-box/ui/WriterProfileBox.tsx
  src/features/community-create-box/index.tsx
  src/features/community-list/index.tsx
  src/features/edit-center-profile/index.tsx
  src/features/find-nearby-activity-map/index.tsx
  src/features/find-nearby-activity-map/indexCss.ts
  src/features/find-nearby-activity-search/index.tsx
  src/features/find-nearby-activity-search/indexCss.ts
  src/features/login-feature/_components/org-login/index.tsx
  src/features/message-create-modal/index.tsx
  src/features/message-read-modal/index.tsx
  src/features/personal-my-page-edit-profile/index.tsx
  src/features/profile-page-img-box/index.tsx
  src/features/review-read-modal/index.tsx
  src/pages/aidrq-detail-admin-page/ui/button-group/index.tsx
  src/pages/center-contact-page/ui/contact-form/index.tsx
Labels: enhancement

#319 ♻️ [#317] Refactor: 기관 마이페이지, 버튼 컴포넌트 적용
  src/features/aidreq-detail-admin-info/_components/applicant-status/index.tsx
  src/features/aidreq-detail-admin-info/indexCss.ts
  src/features/edit-center-profile/_components/profile-edit-form/index.tsx
  src/features/edit-center-profile/_components/profile-edit-form/indexCss.ts
  src/features/edit-center-profile/index.tsx
  src/features/edit-center-profile/indexCss.ts
  src/features/manage-center-post-set/_components/go-aidreq-set/index.tsx
  src/features/manage-center-post-set/_components/go-aidreq-set/indexCss.ts
  src/features/register-goods/_components/register-bar/index.tsx
  src/features/register-goods/_components/register-bar/indexCss.ts
  src/features/register-goods/index.tsx
  src/pages/aidrq-detail-admin-page/ui/button-group/index.tsx
  src/pages/aidrq-detail-admin-page/ui/button-group/indexCss.ts
Labels: enhancement

#320 318 feature button컴포넌트 재사용하기
  src/components/applicant-list-item/index.tsx
  src/components/applicant-list-item/indexCss.ts
  src/components/search-bar/filter-search/ui/filter-box/index.tsx
  src/components/search-bar/filter-search/ui/filter-box/indexCss.ts
  src/components/search-bar/nonfilter-search/index.tsx
  src/components/search-bar/nonfilter-search/indexCss.ts
  src/components/write-aidreq-button/index.tsx
  src/components/write-aidreq-button/indexCss.ts
  src/features/aidreq-detail-center-profile/_components/button-container/index.tsx
  src/features/aidreq-detail-center-profile/_components/button-container/indexCss.ts
  src/pages/aidrq-create-page/index.tsx
  src/pages/aidrq-create-page/indexCss.ts
  src/pages/aidrq-detail-page/index.tsx
  src/pages/aidrq-detail-page/indexCss.ts
  src/pages/aidrq-modify-page/ui/info-modify/index.tsx
  src/pages/aidrq-modify-page/ui/info-modify/indexCss.ts
  src/pages/aidrq-modify-page/ui/location-modify/index.tsx
  src/pages/aidrq-modify-page/ui/location-modify/indexCss.ts
Labels: Feature

#328 ✨ [#327] Feature: 모집글 삭제 api 연결 완료
  src/pages/aidrq-detail-admin-page/ui/button-group/index.tsx
  src/pages/aidrq-detail-admin-page/ui/button-group/indexCss.ts
  src/store/queries/aidreq-detail-admin-query/useAidRqDetail.ts
Labels: Feature

#332 ✨feat:main에서 관심기관 리스트 불러와서 저장
  src/pages/main-page/MainPage.tsx
  src/store/stores/interest-center/interestStore.ts
Labels: Feature

#334 ✨feat:관심기관 기능 구현완료
  src/components/interest-heart/logic/useInterest.ts
  src/store/stores/interest-center/interestStore.ts
Labels: Feature

#336 🐛fix:210에러조건처리 / SSE및notification관련 콘솔 삭제
  src/layout/header/Header.tsx
  src/store/queries/aidreq-detail-volunteer-query/usePresentStatus.ts
Labels: bug

#351 ✨feat:알림기능추가구현완료
  src/components/alert-item/index.tsx
  src/components/alert-item/indexCss.ts
  src/features/alert/index.tsx
  src/features/alert/indexCss.ts
  src/features/alert/logic/all-read/deleteAllNotifications.ts
  src/layout/header/Header.tsx
Labels: Feature

#361 🐛fix:cicd오류디버깅
  src/shared/types/location/nearbyLocation.ts
Labels: bug
