Repository prgrms-web-devcourse-final-project/WEB1_1_Bongdari_FE, pull requests merged in 2025-02, with the labels that each got.

#554 ✨feat:RoleId가져오기
  src/pages/center-my-page/index.tsx
  src/pages/success-page/index.tsx
  src/store/stores/login/loginStore.ts
Labels: Feature

#556 🐛fix:cicd오류개선
  src/pages/main-page/_components/localTestBox/index.tsx
  src/pages/main-page/_components/localTestBoxVolun/index.tsx
Labels: bug

#559 🐛fix:상세정보입력여부에 따라 라우팅처리
  src/api/routes/index.tsx
  src/components/route/ProtectedRoute.tsx
  src/pages/detail-info-page/center/index.tsx
  src/pages/detail-info-page/volunteer/index.tsx
Labels: bug

#565 🐛fix: ProtectedRoute디버깅테스트 및 랭킹디버깅
  src/components/route/ProtectedRoute.tsx
  src/main.tsx
  src/pages/main-page/_components/ranking/index.tsx
  src/store/queries/main-page-common-query/useFetchMainCommunity.ts
  src/store/queries/main-page-common-query/useListShort.ts
Labels: bug

#573 ✨feat: 상세정보입력 유효성검사
  src/pages/detail-info-page/volunteer/index.tsx
  src/pages/detail-info-page/volunteer/indexCss.ts
Labels: Feature

#574 Refactor/#572/생년월일 사이트유효성 제거
  src/features/applicant-detail-modal/index.tsx
  src/features/edit-center-profile/_components/profile-edit-form/index.tsx
  src/features/edit-center-profile/index.tsx
  src/features/edit-center-profile/logic/useEditCenterProfile.ts
Labels: enhancement

#576 ✨feat:token을 localStorage에서 관리
  src/api/apis/index.tsx
  src/components/route/ProtectedRoute.tsx
  src/layout/header/Header.tsx
  src/pages/login-page/logic/useLogin.ts
  src/pages/main-page/MainPage.tsx
  src/pages/success-page/index.tsx
  src/store/stores/login/loginStore.ts
Labels: Feature

#580 ✨feat:토큰리프레시 테스트 1차
  src/api/apis/index.tsx
  src/pages/success-page/index.tsx
  src/store/queries/update-login-info/updateLoginInfo.ts
Labels: Feature

#582 ✨feat:로그인 단기토큰 이용 로직
  src/pages/login-page/logic/useLogin.ts
  src/pages/login-page/logic/useSocialLogin.ts
  src/pages/main-page/MainPage.tsx
  src/pages/success-page/index.tsx
Labels: Feature

#584 🐛fix:로그인로직 디버깅 1차
  src/pages/success-page/index.tsx
Labels: bug

#589 🐛fix:관심기관프로필조회 type: center_id->id로변경
  src/features/aidreq-detail-center-profile/_components/info-container/index.tsx
  src/features/profile-page-img-box/index.tsx
  src/features/profile-page-info-box/index.tsx
  src/pages/main-page/MainPage.tsx
  src/shared/types/center-profile/centerProfile.ts
Labels: bug

#596 🐛fix:커뮤니티 작성자 프로필 확인가능 / 기관은 작성 및 댓글 불가
  src/components/inputBox/index.tsx
  src/features/communitiy-detail-comment-box/index.tsx
  src/features/communitiy-detail-content-box/index.tsx
  src/features/communitiy-detail-content-box/logic/useCommunityDetailContent.ts
  src/features/community-list/index.tsx
  src/features/personal-my-page-half-list/index.tsx
  src/pages/main-page/_components/community/indexCss.ts
Labels: bug
