Repository prgrms-web-devcourse-final-project/WEB1_1_Bongdari_FE, pull requests merged in 2025-01, with the labels that each got.

#376 ✨feat: 모집글 등록 시, 유효성검사
  src/components/aidrq-create-date/index.tsx
  src/pages/aidrq-create-page/index.tsx
  src/pages/aidrq-create-page/logic/validateVolunteerData.ts
Labels: Feature

#378 ✨fix:15/19에러수정
  src/features/communitiy-detail-comment-box/index.tsx
  src/features/communitiy-detail-comment-box/ui/Comment.tsx
  src/features/communitiy-detail-comment-box/ui/CommentInput.tsx
  src/features/personal-my-page-half-list/index.tsx
  src/layout/header/Header.tsx
Labels: bug

#384 ✨feat:select컴포넌트수정
  public/assets/imgs/select-arrow.svg
  src/components/select/index.tsx
  src/components/select/indexCss.ts
Labels: Feature

#395 🐛 [#390] Fix: 지원자현황 단건 조회에서 지원자 이메일 필드 삭제
  src/features/applicant-detail-modal/index.tsx
  src/features/applicant-detail-modal/indexCss.ts
Labels: wontfix

#401 Feat/#399/회원상세정보
  src/api/routes/index.tsx
  src/features/aidrq-list-admin/indexCss.ts
  src/pages/detail-info-page/center/index.tsx
  src/pages/detail-info-page/center/indexCss.ts
  src/pages/detail-info-page/index.tsx
  src/pages/detail-info-page/indexCss.ts
  src/pages/detail-info-page/volunteer/index.tsx
  src/store/queries/login-query/useLoginCenter.ts
Labels: Feature

#405 ✨feat:aidrqlistpage 반응형 완료
  src/components/aidreq-list-Item/indexCss.ts
  src/components/search-bar/filter-search/ui/filter-box/indexCss.ts
  src/pages/aidrq-list-page/indexCss.ts
  src/pages/aidrq-list-page/ui/tab/indexCss.ts
Labels: Feature

#409 ✨feat:aidrq 디테일페이지 반응형 완료
  src/features/aidreq-detail-center-profile/_components/button-container/indexCss.ts
  src/features/aidreq-detail-center-profile/_components/info-container/indexCss.ts
  src/features/aidreq-detail-center-profile/_components/picture-container/indexCss.ts
  src/features/aidreq-detail-center-profile/indexCss.ts
  src/features/aidreq-detail-info/_components/recruit-date/indexCss.ts
  src/features/aidreq-detail-info/_components/volunteer-date/indexCss.ts
  src/features/aidreq-detail-info/indexCss.ts
  src/features/aidrq-list-regular/indexCss.ts
  src/pages/aidrq-detail-page/indexCss.ts
  src/pages/aidrq-detail-page/ui/text-content/indexCss.ts
  src/pages/aidrq-detail-page/ui/title/indexCss.ts
Labels: Feature

#413 ✨feat:모집글상세부분 components폴더로 이동
  src/components/aidreq-detail-info/current-recruit/index.tsx
  src/components/aidreq-detail-info/current-recruit/indexCss.ts
  src/components/aidreq-detail-info/location/index.tsx
  src/components/aidreq-detail-info/location/indexCss.ts
  src/components/aidreq-detail-info/recruit-date/index.tsx
  src/components/aidreq-detail-info/recruit-date/indexCss.ts
  src/components/aidreq-detail-info/volunteer-date/index.tsx
  src/components/aidreq-detail-info/volunteer-date/indexCss.ts
  src/features/aidreq-detail-info/index.tsx
Labels: Feature

#418 Feat/#404/기관마이페이지
  src/features/edit-center-profile/_components/image-uploader/indexCss.ts
  src/features/edit-center-profile/_components/profile-edit-form/index.tsx
  src/features/edit-center-profile/_components/profile-edit-form/indexCss.ts
  src/features/edit-center-profile/indexCss.ts
  src/features/manage-center-post-set/_components/message-set/index.tsx
  src/features/manage-center-post-set/_components/message-set/indexCss.ts
  src/features/manage-center-post-set/_components/review-set/index.tsx
  src/features/manage-center-post-set/_components/review-set/indexCss.ts
  src/features/manage-center-post-set/_components/tab-menu/indexCss.ts
  src/features/manage-center-post-set/indexCss.ts
  src/features/message-read-modal/indexCss.ts
  src/features/register-goods/_components/goods-item-box/indexCss.ts
  src/features/register-goods/_components/register-bar/indexCss.ts
  src/features/register-goods/index.tsx
  src/features/register-goods/indexCss.ts
  src/pages/center-my-page/indexCss.ts
Labels: enhancement

#420 ✨ [#419] Feat: 모달 반응형 적용
  src/components/modal/indexCss.ts
Labels: enhancement

#426 Feat/#421/기관모집글관리
  src/pages/admin-aidrq-list-page/index.tsx
  src/pages/admin-aidrq-list-page/indexCss.ts
  src/pages/center-my-page/indexCss.ts
Labels: enhancement

#422 ✨feat:모집글 수정기능 추가구현
  src/pages/aidrq-detail-page/ui/title/indexCss.ts
  src/pages/aidrq-modify-page/index.tsx
  src/pages/aidrq-modify-page/logic/validateVolunteerData.ts
  src/pages/aidrq-modify-page/ui/info-modify/index.tsx
  src/pages/aidrq-modify-page/ui/info-modify/indexCss.ts
  src/pages/aidrq-modify-page/ui/location-modify/index.tsx
  src/store/queries/aidreq-control-center-query/useModifyAidRqLocation.ts
Labels: Feature

#433 ✨feat:header반응형구현
  public/assets/imgs/menu-bar.svg
  src/components/right-menu/index.tsx
  src/components/right-menu/indexCss.ts
  src/components/write-aidreq-button/indexCss.ts
  src/layout/header/Header.tsx
  src/layout/header/HeaderCss.ts
  src/pages/aidrq-modify-page/ui/info-modify/index.tsx
  src/pages/aidrq-modify-page/ui/info-modify/indexCss.ts
Labels: Feature

#438 ✨feat:리뷰여부판별
  src/pages/aidrq-detail-page/index.tsx
  src/shared/types/aidrq-detail/PresentResponse.ts
Labels: Feature

#440 🐛fix:cicd오류디버깅
  src/store/queries/aidreq-detail-volunteer-query/usePresentStatus.ts
Labels: bug

#441 ✨feat:로그인추가기능구현
  src/api/apis/index.tsx
  src/pages/login-page/LoginPage-backup.tsx
  src/pages/login-page/LoginPage.tsx
  src/pages/login-page/LoginPageCss.ts
  src/pages/login-page/LoginPage최종.tsx
  src/pages/login-page/logic/useLogin.ts
  src/pages/main-page/MainPage.tsx
  src/store/queries/login-query/useLoginCenter.ts
  src/store/queries/login-query/useNormalLogin.ts
Labels: Feature

#444 🐛fix:cicd디버깅
  src/features/login-feature/_components/org-login/index.tsx
  src/features/login-feature/_components/org-login/logic/useOrgLogin.ts
  src/pages/login-page/logic/useLogin.ts
Labels: bug

#442 432 feature 기관개인 프로필 페이지 반응형 적용
  src/components/select/indexCss.ts
  src/features/center-profile-prefer-item-box/indexCss.ts
  src/features/center-review-list/index.tsx
  src/features/center-review-list/indexCss.ts
  src/features/manage-center-post-set/_components/review-set/ReviewList.tsx
  src/features/profile-page-img-box/indexCss.ts
  src/features/profile-page-info-box/index.tsx
  src/features/profile-page-info-box/indexCss.ts
  src/pages/center-profile-page/_component/CPPGReviewList.tsx
  src/pages/center-profile-page/_component/CPPGReviewListCss.ts
  src/pages/center-profile-page/_component/CPPGTopCss.ts
  src/pages/center-profile-page/_component/logic/useCenterReview.ts
  src/pages/center-profile-page/index.tsx
  src/pages/center-profile-page/indexCss.ts
  src/pages/personal-profile-page/index.tsx
  src/pages/personal-profile-page/indexCss.ts
  src/store/queries/center-profile-query/useFetchCenterData.ts
Labels: enhancement

#446 🐛fix:cicd디버깅2차
  src/pages/login-page/LoginPage-backup.tsx
Labels: bug

#452 🐛fix:EventPollyfill사용
  package.json
  src/layout/header/Header.tsx
  src/layout/header/HeaderCss.ts
  yarn.lock
Labels: bug

#454 ✨feat:로그인실패시 오류메시지
  src/pages/login-page/LoginPage.tsx
  src/pages/login-page/logic/useLogin.ts
Labels: Feature

#460 ✨feat:모집글등록 추가기능구현
  src/components/aidrq-create-date/indexCss.ts
  src/features/aidrq-create-shared-part/ui/select-container/indexCss.ts
  src/pages/aidrq-create-page/indexCss.ts
  src/pages/aidrq-create-page/ui/recruit-population/indexCss.ts
  src/pages/aidrq-create-page/ui/volunteer-date/indexCss.ts
  src/pages/aidrq-create-page/ui/volunteer-hour/indexCss.ts
  src/shared/hooks/usePostCode.ts
Labels: Feature

#463 ✨feat:수정페이지반응형
  src/pages/aidrq-modify-page/indexCss.ts
  src/pages/aidrq-modify-page/ui/info-modify/indexCss.ts
  src/pages/aidrq-modify-page/ui/location-modify/indexCss.ts
Labels: Feature

#465 ✨feat:메인페이지 반응형
  src/features/aidrq-list-main-page/indexCss.ts
  src/features/main-banner/indexCss.ts
  src/pages/main-page/MainpageCss.ts
  src/pages/main-page/_components/aidrq-recent-list/indexCss.ts
  src/pages/main-page/_components/community/indexCss.ts
Labels: Feature

#467 ✨feat:2025banner
  public/assets/imgs/somemore-banner-v2.jpg
  src/features/main-banner/indexCss.ts
Labels: Feature

#469 🐛fix:logout및footer수정
  src/layout/Layout.tsx
  src/layout/LayoutCss.ts
  src/layout/header/Header.tsx
  src/store/queries/logout-query/useCommonLogout.ts
  src/store/queries/logout-query/useVolunteerLogout.ts
  src/store/stores/login/loginStore.ts
Labels: bug

#471 ✨feat:배포사이트 소셜로그인 테스트
  src/pages/login-page/LoginPage.tsx
  src/pages/login-page/logic/useSocialLogin.ts
Labels: Feature

#476 ✨feat:jwt디코딩 및 소셜로그인로직 복구
  src/pages/login-page/logic/useSocialLogin.ts
  src/pages/main-page/MainPage.tsx
Labels: Feature

#480 ✨feat:수정제출가능여부 판별로직
  src/pages/aidrq-modify-page/ui/info-modify/index.tsx
  src/pages/aidrq-modify-page/ui/location-modify/index.tsx
Labels: Feature

#487 🐛fix:console및props오류개선
  src/components/select/index.tsx
  src/components/select/indexCss.ts
  src/components/tab-button/ui/index.tsx
  src/components/tab-button/ui/indexCss.ts
  src/features/center-profile-prefer-item-box/index.tsx
  src/pages/aidrq-detail-page/index.tsx
Labels: bug

#492 ✨feat:봉사활동모집글에 텍스트에디터 추가
  src/features/aidrq-list-admin/indexCss.ts
  src/pages/aidrq-create-page/ui/explanation/index.tsx
  src/pages/aidrq-create-page/ui/explanation/indexCss.ts
  src/pages/aidrq-modify-page/ui/info-modify/index.tsx
  src/pages/aidrq-modify-page/ui/info-modify/indexCss.ts
Labels: Feature

#494 🐛fix:모집글 상태라벨 조건처리
  src/pages/aidrq-detail-page/ui/title/index.tsx
Labels: bug

#496 ✨feat: review모달 기능추가 및 수정
  src/features/review-create-modal/index.tsx
  src/features/review-create-modal/indexCss.ts
  src/pages/aidrq-detail-page/index.tsx
Labels: Feature

#501 🐛fix:오류개선 및 글자수제한
  src/features/message-create-modal/logic/useSendMail.ts
  src/layout/Layout.tsx
  src/layout/LayoutCss.ts
  src/layout/header/Header.tsx
  src/pages/aidrq-create-page/logic/validateVolunteerData.ts
  src/pages/aidrq-modify-page/logic/validateVolunteerData.ts
Labels: bug

#503 🐛fix:사이트재접 시 오류 개선
  src/pages/main-page/MainPage.tsx
Labels: bug

#505 ✨feat:수정하기버튼 비활성화 스케쥴링
  src/pages/aidrq-detail-admin-page/index.tsx
  src/pages/aidrq-detail-admin-page/ui/button-group/index.tsx
Labels: Feature

#507 🐛fix:mainpage토큰판별방식 수정
  src/pages/login-page/logic/useLogin.ts
  src/pages/main-page/MainPage.tsx
Labels: bug

#512 ✨feat:댓글 글자수제한
  src/features/communitiy-detail-comment-box/logic/useCommunityComment.ts
Labels: Feature

#514 🐛fix:로그인info변경
  src/pages/main-page/MainPage.tsx
Labels: bug

#519 ✨feat:회원가입로직완료
  src/pages/login-page/logic/useLogin.ts
  src/pages/signup-page/index.tsx
  src/store/queries/signup-query/duplicateCheck.ts
  src/store/queries/signup-query/useSignUp.ts
Labels: Feature

#526 ✨feat:봉사랭킹 기능구현
  src/components/tab-button/indexCss.ts
  src/main.tsx
  src/mocks/handlers/index.tsx
  src/mocks/handlers/ranking.mock.ts
  src/pages/main-page/_components/ranking/index.tsx
  src/pages/main-page/_components/ranking/indexCss.ts
  src/pages/main-page/_components/ranking/ui/rank-item/index.tsx
  src/pages/main-page/_components/ranking/ui/rank-item/indexCss.ts
  src/shared/types/ranking-data/RankingDataType.ts
  src/store/queries/main-page-common-query/useFetchRanking.ts
Labels: Feature

#530 🐛fix:중복확인시, input disable처리
  src/components/inputBox/indexCss.ts
  src/pages/signup-page/index.tsx
Labels: bug

#534 ✨feat:알림창 높이고정 및 스크롤구현
  src/features/alert/indexCss.ts
Labels: Feature

#539 ✨feat:지원현황조회api수정
  src/pages/aidrq-detail-page/index.tsx
  src/store/queries/aidreq-detail-volunteer-query/usePresentStatus.ts
Labels: Feature

#542 ✨feat:success페이지 개발
  src/api/routes/index.tsx
  src/pages/login-page/logic/useLogin.ts
  src/pages/main-page/MainPage.tsx
  src/pages/success-page/index.tsx
Labels: Feature

#544 🐛fix:중복확인api수정
  src/store/queries/signup-query/duplicateCheck.ts
Labels: bug

#552 ✨feat:상세정보페이지 로그인로직에 연결
  src/layout/Layout.tsx
  src/pages/detail-info-page/center/index.tsx
  src/pages/detail-info-page/center/indexCss.ts
  src/pages/detail-info-page/center/logic/putCenterInfo.ts
  src/pages/detail-info-page/volunteer/index.tsx
  src/pages/detail-info-page/volunteer/indexCss.ts
  src/pages/detail-info-page/volunteer/logic/putVolunteerInfo.ts
Labels: Feature
